-- MySQL Script generated by MySQL Workbench
-- 06/24/16 09:06:38
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zkpmolfu_banhang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zkpmolfu_banhang` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zkpmolfu_banhang` ;


-- -----------------------------------------------------
-- Table `zkpmolfu_banhang`.`user_salary_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zkpmolfu_banhang`.`user_salary_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `pay_date` DATETIME NOT NULL,
  `next_pay_date` DATE NOT NULL,
  `amount` FLOAT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_salary_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_salary_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zkpmolfu_banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zkpmolfu_banhang`.`user_absent_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zkpmolfu_banhang`.`user_absent_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `requested_date` DATETIME NOT NULL,
  `from` DATE NOT NULL,
  `to` DATE NOT NULL,
  `nbr_working_day` FLOAT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_absent_history_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_absent_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `zkpmolfu_banhang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;